### ISSUE TITLE
sub_send_signed_packet commented out in C bindings, Chrysalis-2 branch

### ISSUE THREAD

**Issue by tsconn23** [iotaledger/streams#109]
## Bug description

I notice the `sub_send_signed_packet` function is commented out of the channels.h file in the tip of the Chrysalis-2 branch

https://github.com/iotaledger/streams/blob/06ac7f3508c1ac0747228f1df2eca364653dbe27/bindings/c/include/iota_streams/channels.h#L175

This would prevent that function from being exported rendering it unusable.

The documentation references this function in the example for how to [send messages](https://github.com/iotaledger/streams/blob/chrysalis-2/docs/libraries/c/examples.md#sending-messages), although the function has six parameters in the docs and only four in this commented out version. There is no other version of `sub_send_signed_packet` provided in channels.h

Seems like a mistake.

**Comment by DyrellC** [comment]
This has been addressed in the updates included in the v1.1.0 release
https://github.com/iotaledger/streams/commit/3d3bfd4c73a06f1ef929291ef6a68113c3ee0bff#diff-da3ba93a0261b329e139772fd87cde8ef2dc18c19dd0ee6887b71da38d18abb4
