### ISSUE TITLE
docs: README is outdated

### ISSUE THREAD

**Issue by albydeca** [iotaledger/streams#114]
## Bug description

Links with docs.iota.org domain contained in README.MD give a 404.

## Rust version

Which version of Rust are you running?

- Rust version: Not relevant

## Hardware specification

What hardware are you using?

- Operating system: Not relevant
- RAM: Not Relevant
- Cores:Not Relevant

- Device: Not Relevant

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Open README.md
2.  click on "documentation portal" button or link further down the page in "Getting started"
3. 

## Expected behaviour
The links correspond to valid IOTA documentation pages

## Actual behaviour

404 errors are thrown

## Errors

https://docs.iota.org/docs/channels/1.3/overview, https://docs.iota.org/docs/iota-streams/1.1/overview give 404

**Comment by arnauorriols** [comment]
Also: getting-started example is outdated

**Comment by arnauorriols** [comment]
Thanks @albydeca for the report! Docs have been migrated to the new documentation portal, https://wiki.iota.org/streams/welcome
