### ISSUE TITLE
bindings/wasm: cannot add a new Public Key to PublicKeys array

### ISSUE THREAD

**Issue by jmcanterafonseca-iota** [iotaledger/streams#115]
## Bug description

On the dev branch:

The Public Key of the Subscriber is available.

```
console.log(subs.clone().get_public_key()); 
```

Then I try to add it to a `PublicKeys` instance to be later used in a send_keyload method. 

```
const publicKeys = new PublicKeys();
publicKeys.add(subs.clone().get_public_key());
```

Error is raised:

```
 [Runtime_Error]: null pointer passed to rust
```

I've tried making a copy of the public key string buffer but no luck either. 

```
const str = Buffer.from(Buffer.from(subs.clone().get_public_key())).toString();
```

**Comment by iuslkae** [comment]
In wasm the null pointer error occurs when in rust (so js() call) you call a function that mutates the state of an object
but you submited a pointer of another and so on. 
You must find where you forgot to use the helper function ```clone()```, it could be somewhere an the beginning of your code.
