### ISSUE TITLE
Author: Reset state 

### ISSUE THREAD

**Issue by kwek20** [iotaledger/streams#127]
## Description

In #113 we added the feature for a subscriber to reset a state.
We decided not to add this for an author, as its easy to break things with the author if not handled properly.
If this gets a decent amount of thumbs, we will add it regardless

## Motivation

Resetting the state is useful to re-read all messages in a stream without creating a new instance

## Requirements

Write a list of what you want this feature to do.

1. Reset state to author
2. Add method to bindings
3. Add to documentation

## Open questions (optional)

Do we really need this?

**Comment by arnauorriols** [comment]
Could you describe the details of what could go wrong when reseting the state by the author?
