### ISSUE TITLE
Feature: Remove async flag/Make streams api async by default

### ISSUE THREAD

**Issue by DyrellC** [iotaledger/streams#133]
## Description

We have had 2 api's available through streams since the introduction of Chrysalis 2.0, and it's clogging up the works. In order to become more compatible with other libraries/tools like `Stronghold` and `DID's` (which are predominantly asynchronous) we need to bring the asynchronous functionality down to the lower api and message processing layers in `iota-streams-app-channels` and `iota-streams-app`. 

## Motivation
To allow for more compatibility with the other IF libraries, as well as more appropriate feature management when dealing with things like the `iota.rs` client. 

## Requirements
1.  Async flag needs to be removed, `sync-client` and `async-client` should be the main feature dependencies
2. Removal of doubled up api on `api/tangle/` layer of `iota-streams-app-channels`
3. Message processing will need to have appropriate async `sizeof`, `wrap` and `unwrap` functions  (required for DID integration)
4. Examples must be updated to include all the `await`'s necessary to reflect the async baseline
5. A universal synchronous wrapper for functionality that can be used for synchronous required operations (for example use in the c bindings) 

## Open questions 
- Should this be a part of 1.1.1 or 1.1.2, or possibly (due to the nature of the change being so breaking) should it be 1.2.0 
- What approach should we take for blocking functions for synchronous use? Should it be a universal macro? Is there a way for us to automatically go about blocking functions for the c bindings without needing extra functions?  

## Are you planning to do it yourself in a pull request?
Yes.

**Comment by arnauorriols** [comment]
Resolved in #136
