### ISSUE TITLE
Fetch Previous Messages errors if Max exceeds available messages

### ISSUE THREAD

**Issue by DyrellC** [iotaledger/streams#134]
## Bug description
The fetch previous messages api call will error out if it tries to retrieve messages too far back. We need to have a stop on it to avoid that error out and instead just return the messages that were found. 

## Steps To reproduce the bug

1. Set up a stream and send 5 signed packets 
2. Try to retrieve 10 previous messages

## Expected behaviour
Will return the 5 available messages as 10 is specified as a "Maximum"

## Actual behaviour
Errors out as it tries to find messages before the announcement

**Comment by arnauorriols** [comment]
Fixed in #170
