### ISSUE TITLE
Wrong preshared key behavior for multi branch

### ISSUE THREAD

**Issue by dominic22** [iotaledger/streams#137]
## Bug description
1. Not able to receive messages from subscriber branch

When creating a multi branch channel with a preshared key for an subscriber (auditor), the auditor is only able to fetch messages from the author but not from a different branch of a subscriber which writes to the channel.

Here is my code sample:
https://codesandbox.io/s/preshared-key-multi-branch-i7ik5

2. Fetches messages of the author although auditor used wrong key when subscribing

In the following code sample I used a different preshared key as it was used by the author when creating the channel. In this case the auditor is still able to decrypt the message of the author.

Code Sample:
https://codesandbox.io/s/wrong-preshared-key-multi-branch-i7ik5?file=/src/index.js

## Rust version

https://github.com/iotaledger/streams/commit/2964da41b2f5629998f39d1ffa95b76a7ef4263a

## Steps To reproduce the bug
See code examples.

## Expected behaviour

1. Auditor is able to fetch messages from all subscribers if the preshared key is added to the `send_keyload` message of the branch.
2. Auditor shouldn't be able to receive this messages since he has the wrong preshared key.

**Comment by kwek20** [comment]
Hmmm its definitely working in rust; https://pastebin.com/pLFRWvtw

Tested from commit: https://github.com/iotaledger/streams/commit/2964da41b2f5629998f39d1ffa95b76a7ef4263a

**Comment by kwek20** [comment]
Right... I see.. :D

When you store a PSK, you get a string back
`let id = author.store_psk(presharedkey);`

Then when you make a PskIds object, you store said id in there. In the example you use you store the `presharedkey` not the id :)

Once you change that on both accounts, your first example works
