### ISSUE TITLE
`fetch_all_next_msgs` not exposed to WASM bindings

### ISSUE THREAD

**Issue by jmcanterafonseca-iota** [iotaledger/streams#171]
## Description

Expose `fetch_all_next_msgs` to WASM bindings

## Motivation

To use such a function from Javascript

## Requirements

Expose the functionality following a similar approach than `fetch_next_msgs`

## Are you planning to do it yourself in a pull request?

No

**Comment by arnauorriols** [comment]
This issue is addressed by #151

**Comment by arnauorriols** [comment]
Also, I suggest reading https://github.com/iotaledger/streams/issues/122

**Comment by jmcanterafonseca-iota** [comment]
@arnauorriols totally agree that fetch_all_msgs must be used with care (only when you know number of messages is low) but given the amount of time it can take to retrieve all messages it would be more sensible for an application to retrieve them progressively so that the user starts seeing something as soon as possible, augmenting the overall responsiveness
