### ISSUE TITLE
Use enums for boolean parameters

### ISSUE THREAD

**Issue by JakeSCahill** [iotaledger/streams#22]
When creating a new `Author` or `Subscriber` instance, it would be clearer if you had to pass something like `WithNtruKeys` or `WithoutNtruKeys` instead of `true` or `false`.

```rust
let mut author = Author::new("", 3, WithNtruKeys);
```

**Comment by arnauorriols** [comment]
The current API, although different from back then, follows the design suggested by this issue. Thanks for the input!
