### ISSUE TITLE
Make error message more helpful

### ISSUE THREAD

**Issue by JakeSCahill** [iotaledger/streams#24]
If a subscriber unwraps the same `Announce` message more than once, this error is returned, which isn't particularly helpful and displays the channel address in trits.

This error is also returned if the subscriber tries to unwrap two different `Announce` messages.

```bash
Got Announce with address 243:[(243,0,0x2a78d9bd590):[|221102102122011020021020010022110200221110002110200000111221112102202100221110210000221222221011010200110000120221220101200212111220021221122102022222001111122100212010210212211210022102221020000211010221102020221220110000111001200102100122212]], but already registered to a channel 243:[(243,0,0x2a78d9bdf90):[|221102102122011020021020010022110200221110002110200000111221112102202100221110210000221222221011010200110000120221220101200212111220021221122102022222001111122100212010210212211210022102221020000211010221102020221220110000111001200102100122212]]
```

Source: https://github.com/iotaledger/streams/blob/6e25ad880ec3ab22d3b2f51b1f4be7e6f18cfc5e/iota-streams-app-channels/src/api/subscriber.rs#L296

## Solution

Firstly, could we display addresses in trytes to make them more friendly to read and compare?

Secondly,  could we make this error clearer by separating the two scenarios?

1. `Subscriber tried to process an announcement with the same channel address more than once: Channel address in trytes

2. Subscriber has already processed an announcement with channel address: Channel address in trytes. Cannot process the new announcement with channel address: Channel address in trytes

**Comment by arnauorriols** [comment]
Addressed by #68
