### ISSUE TITLE
recv_messages.. and send_messages.. don't handle/propagate network errors

### ISSUE THREAD

**Issue by aleb-user** [iotaledger/streams#26]
It sometimes happens that with a bad connection, recv_messages_with_options and send_messages_with_options fail with:
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Json(Error("expected value", line: 1, column: 1)))', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/iota-client-0.3.0/client.rs:328:46`

This error can be traced back to: 

```
/// Receive a message.
    fn recv_messages_with_options
    ....
        let find_resp = self.find_transactions(find_opt)?;
        if let Some(e) = find_resp.error() {
            bail!("Find transactions failed with: {}.", e)
        } else if let Some(hashes) = find_resp.take_hashes() {
-->        let get_resp = self.get_trytes(&hashes)?;
            if let Some(e) = get_resp.error() {
                bail!("Get trytes failed with: {}.", e)
            } else if let Some(trytes) = get_resp.take_trytes() {
                return Ok(bundles_from_trytes(&trytes)
                    .into_iter()
                    .map(|bundle| msg_from_bundle(&bundle))
                    .collect());
            } else {
                bail!("Get trytes contains no trytes.")
            }
        } else {
            bail!("Find transactions contains no hashes.")
        }
    }
```

Where `get_trytes` uses unwrap() on the network call, and the result is handled with "?", so if connection fails, or no response is received from node the entire application chrashes, a more pleasant behavior would be to handle the error or propagate it higher so the developer can handle it

**Comment by DyrellC** [comment]
This extends to other issues as well

**Comment by arnauorriols** [comment]
Code has changed a lot since, but in general `Transport` errors are now properly propagated.
