### ISSUE TITLE
MWM set in send options is overwritten if local_pow is disabled

### ISSUE THREAD

**Issue by aleb-user** [iotaledger/streams#27]
When connected to comnet with remote PoW the message { msg: "MWM too high. MWM: 14, Max allowed: 10" } is returned, even if the send options have been set MWM to a value below 10.

This happens because if remote pow is enabled and send_trytes is called at `iota-streams-app/src/transport/tangle/client.rs:406` the attach options of MWM used at `iota-client-0.3.0/extended/send_trytes.rs:75` are overwritten from 9 to 14 at `iota-client-0.3.0/extended/send_trytes.rs:69`

**Comment by arnauorriols** [comment]
Closing as this issue no longer applies in the latest versions.
