### ISSUE TITLE
Timestamps are in milliseconds instead of seconds

### ISSUE THREAD

**Issue by JakeSCahill** [iotaledger/streams#3]
The `timestamp` field of the Channel transactions are in milliseconds instead of seconds.

This causes tools such as Tangle explorers to display a transaction date way in the future:
![image](https://user-images.githubusercontent.com/45230295/78898006-fabc7c00-7a6a-11ea-89d3-b2c36c3d93d8.png)

https://utils.iota.org/address/VZGHRWHIYKQBOMWSNRFGT9VAXPZASVOPGLYHBIV9NTTAAVAVHTMOZO9XHDDRDGADHRPJWWGJJEWLWPQXY/devnet

**Additional note**
The bundle structure seems strange. Tangle explorers declare them as invalid.

**Comment by semenov-vladyslav** [comment]
Mixed up `timestamp` and `attachment_timestamp`.

**Comment by JakeSCahill** [comment]
@semenov-vladyslav has been fixed?
