### ISSUE TITLE
As a developer, I'd like `send_message()` to return my bundle

### ISSUE THREAD

**Issue by JakeSCahill** [iotaledger/streams#4]
The `send_message()` method sends a channel message to a node, using the `iota_client` instance.

However, the result that's returned from the node is not also returned by the `send_message()` method.

When using the channel app, this makes it difficult to know if the transactions were sent and what the resulting bundle information is.

**Comment by Citrullin** [comment]
Why? When you attach it to the tangle, you don't get anything in return. It's just a function with side-effects. The bundle is stateless. Even though IRI returns a success, it doesn't mean that it actually it already synced with other nodes. The Fallible returns an Error, if it wasn't successful. Therefore, you can already check, if it was sent or not.
https://docs.rs/failure/0.1.5/failure/type.Fallible.html

**Comment by JakeSCahill** [comment]
Right. But you may want to be able to check that the bundle actually propagated through the network. Without the tail transaction hash, it's difficult to check that because if you search by the channel's address, you could get back a lot of spam transactions. You could also search by the tag (message identifier), but you face the same problem.

**Comment by JakeSCahill** [comment]
I think this is a separate issue now.

I think maybe any publisher should send the receiver not only the message identifer but also the transaction hash to avoid processing lots of spam.
