### ISSUE TITLE
Failed to build using Remote dependencies

### ISSUE THREAD

**Issue by Tsangares** [iotaledger/streams#48]
## Bug description

When installing with the following in my `Cargo.toml`

    [dependencies]
    anyhow = { version = "1.0", default-features = false }
    iota-streams = { git = "https://github.com/iotaledger/streams", branch  = "master"}

I receive the error below. Cloning the repo and installing works fine. 

Which version of Rust are you running?

- Rust version: rust-1:1.47.0-1 

## Hardware specification

- Operating system: Arch Linux
- RAM: 8Gb
- Cores: 4
- Device: Macbook Pro 

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1.  Run `cargo new my-library`
2.  Add to `Cargo.toml`
```
[dependencies]
anyhow = { version = "1.0", default-features = false }
iota-streams = { git = "https://github.com/iotaledger/streams", branch  = "master"}
```
2.  Run `cargo build`

## Expected behavior
Build correctly

## Actual behavior

    wil@taxi ~/D/i/secret (master)> cargo build
    Updating crates.io index
    Updating git repository `https://github.com/iotaledger/streams`
    Updating git repository `https://github.com/iotaledger/bee.git`
    Updating git repository `https://github.com/Alex6323/bee-p.git`
    Updating git repository `https://github.com/iotaledger/iota.rs`
    error: no matching package named `bee-ternary` found
    location searched: https://github.com/iotaledger/bee.git?branch=dev
    prerelease package needs to be specified explicitly
    bee-ternary = { version = "0.3.2-alpha" }
    required by package `iota-core v0.2.0-alpha.3 (https://github.com/iotaledger/iota.rs?rev=0ad8e7f#0ad8e7f7)`
        ... which is depended on by `iota-streams-app v1.0.0 (https://github.com/iotaledger/streams?branch=master#762142e8)`
        ... which is depended on by `iota-streams v1.0.0 (https://github.com/iotaledger/streams?branch=master#762142e8)`
        ... which is depended on by `secret v0.1.0 (/mnt/iota/secret)`

Fails to build.

**Comment by kwek20** [comment]
Hey @Tsangares, this is a known bug that happened a week ago when iota.rs did an update. You can set the streams branch to `develop` for now, or better yet specify the new revision/commit in streams until a new release is made:
`iota-streams = { git = "https://github.com/iotaledger/streams", rev = "456347a"}`

**Comment by Tsangares** [comment]
Got it. 

Also, I am a novice to rust and while fiddling with this code, I notice a lot a discrepancies with the docs and examples and stuff. Like on [docs.iota.org,](https://docs.iota.org/docs/channels/1.2/guides/creating-a-new-channel#announcing-a-channel) it says `let announcement = author.announce();` when it should say `let announcement = author.send_announce();` even though I prefer the former syntax.

When I notice thing, how do I suggest an edit to docs.iota.org?

**Comment by kwek20** [comment]
Youre on 1.2, change the docs.iota page to 1.3! We moved away from separating `create` and `send`, to make it easier for people.

https://docs.iota.org/docs/channels/1.3/overview

**Comment by dangenendt** [comment]
Hm... i tried it with the recommended dependency definition but i still get the exact same error message. 🧐

**Comment by AntonAndell** [comment]
Is there any fix to this yet, trying to use the example at https://github.com/iotaledger/channels-examples, i however get the same error and following others with similar issues have not helped. I get the error: no matching package named `bee-ternary` found for all the settings of the cargo file i tried. Any tips would be greatly appreciated.

**Comment by Tsangares** [comment]
@AntonAndell 
Change 
```iota-streams = { git = "https://github.com/iotaledger/streams", branch  = "master"}```
To this
```iota-streams = { git = "https://github.com/iotaledger/streams", branch  = "develop"}```
In cargo toml

**Comment by vivekkohli536** [comment]
```
[package]
name = "author"
version = "0.1.0"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0", default-features = false }
iota-streams = { git = "https://github.com/iotaledger/streams", branch  = "develop"}
iota-conversion = { git = "https://github.com/iotaledger/iota.rs", rev = "03cf531" }
iota-core = { git = "https://github.com/iotaledger/iota.rs", branch = "dev" }
```

but still getting the same issue:

```
error: no matching package named `bee-ternary` found
location searched: https://github.com/iotaledger/bee.git?branch=dev
prerelease package needs to be specified explicitly
bee-ternary = { version = "0.4.1-alpha" }
required by package `iota-core v0.2.0-alpha.3 (https://github.com/semenov-vladyslav/iota.rs?branch=iota-1.0-surf#945bf33d)`
    ... which is depended on by `iota-streams-app v1.0.1 (https://github.com/iotaledger/streams?branch=develop#e8123515)`
    ... which is depended on by `iota-streams v1.0.0 (https://github.com/iotaledger/streams?branch=develop#e8123515)`
    ... which is depended on by `author v0.1.0 (/home/fullstackdev/projects/fetch/aea-iota-stream)`
  ```
