### ISSUE TITLE
Rename Author to Publisher

### ISSUE THREAD

**Issue by Citrullin** [iotaledger/streams#5]
The Publish Subscribe is a well known pattern. Since streams fits into this pattern, as a developer it feels more natural use the naming convention of it.

**Comment by semenov-vladyslav** [comment]
Subscribers can also publish messages: Subscribe, Unsubscribe, Keyload, TaggedPacket. It can be confusing when talking about message publisher as it can be either Publisher or a Subscriber. Author/Subscriber terminology is taken from youtube, which fits Channels app quite well IMO.

**Comment by JakeSCahill** [comment]
Agreed, maybe we can close this @semenov-vladyslav
