### ISSUE TITLE
Support async transport in Channels

### ISSUE THREAD

**Issue by semenov-vladyslav** [iotaledger/streams#53]
## Description

Implement async transport in Author/Subscriber API.

## Motivation

Channels Author/Subscriber API is parametrized with Transport. Synchronous transport is supported for the moment. Asynchronous transport is (more) suitable for asynchronous/multithreaded applications, wasm and other targets willing to use asynchronous I/O.

## Requirements

Write a list of what you want this feature to do.

1. Support `async` cargo feature in channels crate.
2. Support `async` in bindings.

## Open questions (optional)

1. How does c should support async?
2. How does wasm should support async?

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by arnauorriols** [comment]
Already done
