### ISSUE TITLE
Propagate Dependency errors to user

### ISSUE THREAD

**Issue by DyrellC** [iotaledger/streams#64]
## Description
Wherever we become reliant on a potentially error producing dependency, we need to pass any errors that occur at this point up to the user end for easy debugging. 

## Motivation
There have already been instances where a dependency within the client library breaks in some way and hunting down the source and patching becomes difficult. 

## Requirements
- [ ] If an error is caused by a dependency, ensure that error message is passed up through the code
- [ ] Propagate `iota.rs` errors up to the user side

## Open questions 
What degree of granularity do we want on these propagated errors (full stack trace or just message)?

**Comment by arnauorriols** [comment]
addressed by #68
