### ISSUE TITLE
Clippy, GH Actions and code clean up Pt. 2

### ISSUE THREAD

**Issue by kwek20** [iotaledger/streams#78]
## Description

- [ ] remove all clippy allows
	example: #[allow(clippy::module_inception)]
	example: #[allow(dead_code)]
- [ ] TODOs in the code
- [ ] Add testing of bindings by compiling
- [ ] Add "iota-streams-app-channels-example" building

## Motivation

Cleaner code = better code

**Comment by arnauorriols** [comment]
Let's close this issue in favour of a continuous-cleanup approach.
