### ISSUE TITLE
bindings/wasm => build fails due to "wasm-pack: command not found "

### ISSUE THREAD

**Issue by sobolev-alexey** [iotaledger/streams#81]
1. Navigate to `bindings/wasm`
2. Install packages with `npm i` or `yarn`
3. Build project with `npm run build` or `yarn build`
4. Error is shown
```
$ npm run build:web && npm run build:nodejs

> iota-streams-wasm@0.0.1 build:web
> wasm-pack build --target web --out-dir wasm-web && node ./build/web && rm ./wasm-web/.gitignore

sh: wasm-pack: command not found
```

**Fix**: Add missing package to the list of dependencies
package.json
```
  "devDependencies": {
    ...
    "wasm-pack": "^0.9.1",
    ...
  },
```

**Comment by kwek20** [comment]
Fair enough, didnt show up since i have it on global :)

Added in https://github.com/iotaledger/streams/commit/1625179c3064673616bb705153fc939e936b4151
