### ISSUE TITLE
Error Building C Bindings

### ISSUE THREAD

**Issue by tsconn23** [iotaledger/streams#96]
## Bug description

I am attempting to build the C bindings by following the README. However when I execute the `make` step, I receive an error.

## Rust version

Which version of Rust are you running?

- 1.52.1

## Hardware specification

What hardware are you using?

- Operating system: Ubuntu 20.04.2 LTS
- RAM: 16GB
- Cores: 4
- Device: VMWare Workstation Pro VM

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Navigate to the C Bindings [README](https://github.com/iotaledger/streams/tree/develop/bindings/c)
2. Follow the directions up to where it says run `make`. I made no changes to the `CMakeLists.txt` file.
3. Error

## Expected behaviour

I expected to have a C library I could then embed in my project.

## Actual behaviour

I get the error shown below

## Errors

```
Scanning dependencies of target fakeTarget
error: Found argument '--debug' which wasn't expected, or isn't valid in this context

USAGE:
    cargo build [OPTIONS]

For more information try --help
make[2]: *** [CMakeFiles/fakeTarget.dir/build.make:57: CMakeFiles/fakeTarget] Error 1
make[1]: *** [CMakeFiles/Makefile2:77: CMakeFiles/fakeTarget.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

```

**Comment by sascha1337** [comment]
could you provide more information about your installed build tools gcc and so on, including your env variables and so on ? 
is it a freshly installed system? what apt packages were being installed, before running `cmake .` and `make` ?
Try to make your building process more verbose, and / or post more detailed logs / generated files of cmake, so i can have a deeper look at your stack, sir.

**Comment by tsconn23** [comment]
Thanks for the reply.

Respectfully, it seems to me the cause of the problem is in the error message itself. [This commit](https://github.com/iotaledger/streams/commit/34ffe2c45bcf9b16be1f3466f89aaafdab914992) changed the CMakeLists.txt file to provide a `--debug` build flag to Cargo and Cargo is saying the arg isn't valid. The `cargo build` [docs](https://doc.rust-lang.org/cargo/commands/cargo-build.html) provide no mention of a supported `--debug` build flag.

To unblock myself, I have instead checked out a branch for tag 1.0.1 as I figure that will probably be more stable than working off the `develop` branch. After doing so I was able to execute the steps in the README without issue.

**Comment by DyrellC** [comment]
Yes it is definitely because of the `--debug` flag being present. It's been fixed and updated now. Let me know if you run into any other issues with the bindings. Closing for now.
